# Generated by Django 3.2.8 on 2022-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetvillaApp', '0002_remove_product_subcetegory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prodname',
            field=models.CharField(max_length=50, verbose_name='product Name '),
        ),
    ]
