# Generated by Django 3.2.8 on 2022-06-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetvillaApp', '0003_alter_product_prodname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Name ')),
                ('email', models.EmailField(default='', max_length=30, verbose_name='Email')),
                ('mobNo', models.IntegerField(default='', verbose_name='Mobile No')),
                ('detail', models.CharField(default='', max_length=500, verbose_name='Description')),
            ],
        ),
    ]
