# Generated by Django 3.2.8 on 2022-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetvillaApp', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mobNo',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=70),
        ),
    ]
