# Generated by Django 3.2.8 on 2022-09-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetvillaApp', '0007_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
